version: '3.3'
volumes:
  redis-data:
    driver: local
  data-db:
  # app:
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - data-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_diversitech
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
